
services:
  # Oracle Database 23ai Free (Source) - ARM64 Native with Integrated Extract Support
  oracle-free:
    image: container-registry.oracle.com/database/free:latest
    container_name: oracle-free-source
    hostname: oracle-free
    environment:
      - ORACLE_PWD=Oracle123!
      - ORACLE_CHARACTERSET=AL32UTF8
      - ORACLE_SID=FREE
      - ORACLE_PDB=FREEPDB1
      - INIT_SGA_SIZE=2048
      - INIT_PGA_SIZE=1024
    ports:
      - "1521:1521"
      - "5500:5500"
    volumes:
      - oracle_free_data:/opt/oracle/oradata
      - ./scripts/oracle-free:/opt/oracle/scripts/setup
      - ./configs/oracle-free:/opt/oracle/scripts/configs
      - ./logs/oracle-free:/opt/oracle/diag
    networks:
      - gg-network
    healthcheck:
      test: ["CMD", "sqlplus", "-s", "sys/Oracle123!@localhost:1521/FREE as sysdba", "<<<", "SELECT 1 FROM dual;"]
      timeout: 45s
      retries: 12
      start_period: 90s  # 23ai Free starts faster than EE
      interval: 30s
    shm_size: 2g  # Required for proper Oracle performance

  # PostgreSQL Database (Target)
  postgresql:
    image: postgres:15
    container_name: postgresql-target
    hostname: postgresql
    environment:
      - POSTGRES_DB=targetdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Postgres123!
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/postgresql:/docker-entrypoint-initdb.d
      - ./configs/postgresql:/etc/postgresql
      - ./logs/postgresql:/var/log/postgresql
    networks:
      - gg-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d targetdb"]
      timeout: 10s
      retries: 5
      start_period: 30s
      interval: 10s

  # GoldenGate (Handles both Extract from Oracle Free and Replicat to PostgreSQL)
  goldengate:
    image: container-registry.oracle.com/goldengate/goldengate-free:latest
    platform: linux/amd64  # Force AMD64 emulation on ARM64 Mac
    container_name: gg-replication
    hostname: gg-replication
    environment:
      - OGG_DEPLOYMENT=OracleFreeToPostgreSQL
      - OGG_ADMIN_PWD=GGAdmin123!
      - OGG_SECURE=false
    ports:
      - "9200:8080"
      - "9201:80"
      - "9021:9021"
    volumes:
      - gg_data:/opt/oracle/ogg/var
      - gg_u02_data:/u02
      - gg_u03_data:/u03
      - ./configs/goldengate:/opt/oracle/ogg/dirprm
      - ./scripts/goldengate:/opt/oracle/ogg/scripts
      - ./logs/goldengate:/opt/oracle/ogg/ggserr
    networks:
      - gg-network
    depends_on:
      oracle-free:
        condition: service_healthy
      postgresql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-s", "http://localhost:8080/health"]
      timeout: 10s
      retries: 5
      start_period: 60s
      interval: 30s

volumes:
  oracle_free_data:
    driver: local
  postgres_data:
    driver: local
  gg_data:
    driver: local
  gg_u02_data:
    driver: local
  gg_u03_data:
    driver: local

networks:
  gg-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
