services:
  # Oracle Enterprise Edition Database (Source) - x86 Emulated
  oracle-ee:
    image: container-registry.oracle.com/database/enterprise:latest
    container_name: oracle-ee-source
    hostname: oracle-ee
    environment:
      - ORACLE_PWD=Oracle123!
      - ORACLE_CHARACTERSET=AL32UTF8
      - ORACLE_SID=ORCL
      - ORACLE_PDB=ORCLPDB1
      - INIT_SGA_SIZE=2048
      - INIT_PGA_SIZE=1024
      - ORACLE_EDITION=EE
    ports:
      - "1521:1521"
      - "5500:5500"
    volumes:
      - oracle_ee_data:/opt/oracle/oradata
      - ./scripts/oracle-free:/docker-entrypoint-initdb.d/startup
      - ./configs/oracle-free:/opt/oracle/scripts/setup
      - ./logs/oracle-free:/opt/oracle/diag
    networks:
      - gg-network
    healthcheck:
      test: ["CMD", "sqlplus", "-s", "sys/Oracle123!@localhost:1521/ORCL as sysdba", "<<<", "SELECT 1 FROM dual;"]
      timeout: 60s
      retries: 15
      start_period: 180s  # EE takes much longer to start on ARM
      interval: 45s
    shm_size: 4g  # More memory for EE on emulation

  # PostgreSQL Database (Target)
  postgresql:
    image: postgres:15
    container_name: postgresql-target
    hostname: postgresql
    environment:
      - POSTGRES_DB=targetdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Postgres123!
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/postgresql:/docker-entrypoint-initdb.d
      - ./configs/postgresql:/etc/postgresql
      - ./logs/postgresql:/var/log/postgresql
    networks:
      - gg-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d targetdb"]
      timeout: 10s
      retries: 5
      start_period: 30s
      interval: 10s

  # GoldenGate (Handles both Extract from Oracle EE and Replicat to PostgreSQL)
  goldengate:
    image: container-registry.oracle.com/goldengate/goldengate-free:latest
    platform: linux/amd64  # Force AMD64 emulation on ARM64 Mac
    container_name: gg-replication-ee
    hostname: gg-replication-ee
    environment:
      - OGG_DEPLOYMENT=OracleEEToPostgreSQL
      - OGG_ADMIN_PWD=ggadmin123
      - OGG_SECURE=false
    ports:
      - "9200:80"
      - "9021:9021"
    volumes:
      - gg_data:/opt/oracle/ogg/var
      - ./configs/goldengate:/opt/oracle/ogg/dirprm
      - ./scripts/goldengate:/opt/oracle/ogg/scripts
      - ./logs/goldengate:/opt/oracle/ogg/ggserr
    networks:
      - gg-network
    depends_on:
      oracle-ee:
        condition: service_healthy
      postgresql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-s", "http://localhost:80/oggf/"]
      timeout: 10s
      retries: 5
      start_period: 60s
      interval: 30s

volumes:
  oracle_ee_data:
    driver: local
  postgres_data:
    driver: local
  gg_data:
    driver: local

networks:
  gg-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16